name: check
on:
  workflow_dispatch:

jobs:
  resolverscheck:
    runs-on: ubuntu-latest
    steps:
      - name: resolvers check
        run: |
          git clone https://github.com/dnscrypt/dnscrypt-resolvers.git
          cd dnscrypt-resolvers
          .github/workflows/resolverscheck.sh >> ../../../resolverscheck.txt
          mkdir -p .github/workflows
          wget -qO .github/workflows/main.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/main.yml &> /dev/null
          git config --global init.defaultBranch main
          git init
          git add .
          git config user.name "yaskaza"
          git config user.email "134995220+yaskaza@users.noreply.github.com"
          git commit -m "caddy binary"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push origin main --force

