name: check
on:
  workflow_dispatch:

jobs:
  resolverscheck:
    runs-on: ubuntu-latest
    steps:
      - name: resolvers check
        run: |
          git clone https://github.com/dnscrypt/dnscrypt-resolvers.git
          cd dnscrypt-resolvers
          .github/workflows/resolverscheck.sh
