name: check
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: resolvers check
        run: |
          rm -rf *
          git clone https://github.com/dnscrypt/dnscrypt-resolvers.git
          cd dnscrypt-resolvers
          .github/workflows/prcheck.sh >> ../prcheck.txt
          .github/workflows/resolverscheck.sh >> ../resolverscheck.txt
          rm -rf ../dnscrypt-resolvers
          cd ../
          sort -u resolverscheck.txt
          # cat resolverscheck.txt | grep '/ipv6/d' >> checkresolvers.txt
          # rm -rf resolverscheck.txt
      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
          
